# Generated by Django 2.2.6 on 2019-10-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsmodel',
            name='description',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='credentialsmodel',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
