# Generated by Django 2.2.6 on 2019-10-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamApp', '0002_auto_20191010_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('blockchain_account_name', models.CharField(max_length=30)),
            ],
        ),
    ]
